### ISSUE TITLE
Local example docker compose - unauthorized

### ISSUE THREAD

**Issue by danprueitt** [intergral/deep#57]
**Describe the bug**
Not sure if this is considered a bug but I expected the example to be runnable to test the project without creating a sample app.

When trying to run the docker-compose.yml in the local example, I get an `unauthorized` error from the docker daemon.

```
docker compose up -d
[+] Running 4/4
 ✘ prometheus Error                                                                     0.4s
 ✘ test_app Error                                                                       0.4s
 ✘ grafana Error                                                                        0.4s
 ✘ deep Error                                                                           0.4s
Error response from daemon: Head "https://ghcr.io/v2/intergral/deep-python-client/manifests/simple-app": unauthorized
```

**To Reproduce**
Try to pull the images without logging into/authorizing docker against any docker registries.

**Expected behavior**
I expected to be able to run the example locally by running the docker compose file.

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS 
 - Kernel: 6.4.6-76060406-generic
 - Docker version: 24.0.5, build ced0996

**Comment by Umaaz** [comment]
It should be, seems the python docker image is not public. Let me take a look.

**Comment by Umaaz** [comment]
Seems that ghcr repository always needs to be logged in. 

Also seems that at some point I moved the other examples (debug, etc) to use the same image but from docker.hub. So I have checked and updated the other examples.
